package main

import "fmt"

// Main
func main() {
	fmt.Println("CdBranch --------------------------------------")
	CdBranch()
	fmt.Println("Arrays --------------------------------------")
	Arrays()
	fmt.Println("Slices --------------------------------------")
	Slices()
	fmt.Println("Maps --------------------------------------")
	Maps()
	fmt.Println("Range --------------------------------------")
	Range()
	fmt.Println("Fancs --------------------------------------")
	Fancs()
	fmt.Println("Methods --------------------------------------")
	Methods()
	fmt.Println("Interfaces --------------------------------------")
	Interfaces()
	fmt.Println("ErrorTest --------------------------------------")
	ErrorTest()
	fmt.Println("SelectTest --------------------------------------")
	SelectTest()
	fmt.Println("NonBlocking --------------------------------------")
	NonBlocking()
	fmt.Println("ClosingCh --------------------------------------")
	ClosingCh()
	fmt.Println("TimersTickers --------------------------------------")
	TimersTickers()
	fmt.Println("Workers --------------------------------------")
	Workers()
	fmt.Println("MutexStateful --------------------------------------")
	MutexStateful()
	fmt.Println("CollectionFunc --------------------------------------")
	CollectionFunc()
	fmt.Println("Epoch --------------------------------------")
	Epoch()
	fmt.Println("JSON --------------------------------------")
	JSON()
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
	fmt.Println("ClosingCh --------------------------------------")
}
